/**
 * 前后端共享错误码。
 * 命名格式：E_<领域>_<细节>
 */
const ERRORS = {
  // 鉴权相关
  E_AUTH_REQUIRED: "E_AUTH_REQUIRED",
  E_AUTH_INVALID_TOKEN: "E_AUTH_INVALID_TOKEN",
  E_AUTH_LOGIN_FAILED: "E_AUTH_LOGIN_FAILED",

  // 房间相关
  E_ROOM_NOT_FOUND: "E_ROOM_NOT_FOUND",
  E_ROOM_FULL: "E_ROOM_FULL",
  E_ROOM_ALREADY_IN: "E_ROOM_ALREADY_IN",
  E_ROOM_NOT_IN: "E_ROOM_NOT_IN",
  E_ROOM_ALREADY_STARTED: "E_ROOM_ALREADY_STARTED",
  E_ROOM_NOT_OWNER: "E_ROOM_NOT_OWNER",
  E_ROOM_INVALID_STATE: "E_ROOM_INVALID_STATE",

  // 牌局流程相关
  E_GAME_NOT_FOUND: "E_GAME_NOT_FOUND",
  E_GAME_NOT_STARTED: "E_GAME_NOT_STARTED",
  E_NOT_YOUR_TURN: "E_NOT_YOUR_TURN",
  E_INVALID_PHASE: "E_INVALID_PHASE",
  E_INVALID_ACTION: "E_INVALID_ACTION",
  E_ILLEGAL_TILE: "E_ILLEGAL_TILE",
  E_ACTION_WINDOW_CLOSED: "E_ACTION_WINDOW_CLOSED",
  E_SEQ_CONFLICT: "E_SEQ_CONFLICT",
  E_REQ_DUPLICATED: "E_REQ_DUPLICATED",
  E_RECONNECT_FAILED: "E_RECONNECT_FAILED",

  // 基础设施相关
  E_INTERNAL: "E_INTERNAL",
  E_BAD_REQUEST: "E_BAD_REQUEST",
  E_RATE_LIMITED: "E_RATE_LIMITED",
};

const ERROR_MESSAGES = {
  [ERRORS.E_AUTH_REQUIRED]: "需要先登录",
  [ERRORS.E_AUTH_INVALID_TOKEN]: "登录态失效，请重新登录",
  [ERRORS.E_AUTH_LOGIN_FAILED]: "微信登录失败",

  [ERRORS.E_ROOM_NOT_FOUND]: "房间不存在",
  [ERRORS.E_ROOM_FULL]: "房间已满",
  [ERRORS.E_ROOM_ALREADY_IN]: "你已在房间中",
  [ERRORS.E_ROOM_NOT_IN]: "你不在该房间",
  [ERRORS.E_ROOM_ALREADY_STARTED]: "房间已开局",
  [ERRORS.E_ROOM_NOT_OWNER]: "只有房主可操作",
  [ERRORS.E_ROOM_INVALID_STATE]: "房间状态不允许此操作",

  [ERRORS.E_GAME_NOT_FOUND]: "牌局不存在",
  [ERRORS.E_GAME_NOT_STARTED]: "牌局未开始",
  [ERRORS.E_NOT_YOUR_TURN]: "当前不是你的回合",
  [ERRORS.E_INVALID_PHASE]: "当前阶段不允许此操作",
  [ERRORS.E_INVALID_ACTION]: "动作不合法",
  [ERRORS.E_ILLEGAL_TILE]: "无效牌或不可打出",
  [ERRORS.E_ACTION_WINDOW_CLOSED]: "响应窗口已关闭",
  [ERRORS.E_SEQ_CONFLICT]: "消息顺序冲突，请重连同步",
  [ERRORS.E_REQ_DUPLICATED]: "重复请求已忽略",
  [ERRORS.E_RECONNECT_FAILED]: "恢复牌局失败，请重进房间",

  [ERRORS.E_INTERNAL]: "服务器异常",
  [ERRORS.E_BAD_REQUEST]: "请求参数错误",
  [ERRORS.E_RATE_LIMITED]: "请求过于频繁，请稍后重试",
};

module.exports = {
  ERRORS,
  ERROR_MESSAGES,
};
